# Generated by Django 6.1 on 2026-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending_review', max_length=20),
        ),
    ]
