# Generated by Django 6.1 on 2026-08-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
